apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: test3
  namespace: sdouglas1
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: test-application
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: test3
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: test3-
      labels:
        build.appstudio.openshift.io/application: test-application
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: test3
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: sdouglas1
    spec:
      params:
      - name: git-url
        value: https://github.com/stuartwdouglas/code-with-quarkus
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:sdouglas1-test3-$(tt.params.git-revision)
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:ad4c34b71d468a991450b0091cd96765471ed82d
        name: java-builder
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: test3/$(tt.params.git-revision)
    status: {}
status: {}
